name: JaiMy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+53

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.4
  firebase_storage: ^4.0.1
  firebase_core: ^0.5.3
  firebase_analytics: ^5.0.2
  amazon_s3_cognito: ^0.5.2
  aws_s3: ^0.1.1+hotfix.5
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  flutter_session: ^0.1.1
  dio: ^3.0.10
  carousel_slider: ^2.2.1
  path: any
  mobile_popup: ^1.2.0
  flutter_staggered_grid_view: ^0.3.2
  hexcolor: ^1.0.4
  permission_handler: ^5.0.1+1
  flutter_downloader: ^1.4.4
  charts_flutter: ^0.9.0
  http: ^0.12.1
  flutter_neumorphic: ^3.0.1
  assets_audio_player: ^2.0.13+8
  sqflite: any
  path_provider: any
  path_provider_macos: ^0.0.1
  intl: ^0.16.1
  page_transition: "^1.1.7+2"
  flare_flutter: ^2.0.6
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/know/
    - assets/relex/
    - assets/emotion/
    - assets/rank/
    - assets/sex/
    - assets/icon/
    - assets/badges/
    - assets/game/
    - assets/json/
    - assets/rate/
    - assets/canon/
    - assets/intro/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FCLamoon
      fonts:
        - asset: fonts/FC-Lamoon-Regular.ttf
        - asset: fonts/FC-Lamoon-Bold.ttf
          weight: 700
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
